version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: devnet
      MYSQL_DATABASE: devnet
      MYSQL_USER: devnet_user
      MYSQL_PASSWORD: devnet_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
